name: Build PR documentation

# WARNING: As this workflow supports the pull_request_target event, please exercise extra care when editing it.

on:
  workflow_dispatch:
  pull_request_target:
    branches: [ main ]
    types: [ opened, synchronize, reopened, labeled ]
    paths:
      - "optimum/**.py"
      - "docs/**.mdx"
      - "docs/**.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  authorize:
    if: (github.event.action == 'labeled' && github.event.label.name == 'build-pr-doc') || github.event_name != 'pull_request_target' || (! github.event.pull_request.head.repo.fork)
    runs-on: ubuntu-latest
    steps:
      - run: true
